/*******************************************************************************
 * This file is part of cVoronoi.
 * Copyright (c) 2020 Bert Vandenbroucke (bert.vandenbroucke@gmail.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/

/**
 * @file voronoi.h
 *
 * @brief 2D Voronoi grid.
 *
 * @author Bert Vandenbroucke (bert.vandenbroucke@ugent.be)
 */

#ifndef SWIFT_VORONOI_H
#define SWIFT_VORONOI_H

#include "part.h"
#include "voronoi.h"

#include <string.h>

/*! @brief Store the edges of faces (so that the actual Voronoi grid can be
 *  reconstructed). */
#define VORONOI_STORE_CONNECTIONS

/*! @brief Store information about the number of faces per cell. */
#define VORONOI_STORE_CELL_STATS

/*! @brief Store cell generators. */
#define VORONOI_STORE_GENERATORS

/**
 * @brief Voronoi interface.
 *
 * An interface is a connection between two neighbouring Voronoi cells. It is
 * completely defined by the indices of the generators that generate the two
 * neighbouring cells, a surface area and a midpoint position.
 */
struct voronoi_pair {
  /*! Index of the generator on the left of the interface (always a particle
   *  within the local cell). */
  int left;

  /*! Index of the generator on the right of the interface (can be a local
   *  particle, but also a particle in a neighbouring cell). */
  int right;

  /*! Surface area of the interface. */
  double surface_area;

  /*! Midpoint of the interface. */
  double midpoint[2];

#ifdef VORONOI_STORE_CONNECTIONS
  /*! First vertex of the interface. */
  double a[2];
  /*! Second vertex of the interface. */
  double b[2];
#endif
};

/**
 * @brief Voronoi cell.
 *
 * A cell stores geometrical information about a Voronoi cell: its volume and
 * the location of its centroid.
 */
struct voronoi_cell_new {
  /*! Cell volume. */
  double volume;

  /*! Cell centroid. */
  double centroid[2];

#ifdef VORONOI_STORE_GENERATORS
  double generator[2];
#endif

#ifdef VORONOI_STORE_CELL_STATS
  /*! Number of faces of this cell. */
  int nface;
#endif
};

/**
 * @brief Voronoi grid.
 *
 * The grid stores a copy of the coordinates of the grid generators, the
 * coordinates of the grid vertices and the edge connections that make up the
 * grid. For every generator, it stores the number of vertices for the cell
 * generated by it, and the offset of the cell edges in the edge array.
 */
struct voronoi {

  /*! @brief Voronoi cells. */
  struct voronoi_cell_new *cells;

  /*! @brief Number of cells (and number of generators). */
  int number_of_cells;

  struct voronoi_pair *pairs[27];
  int pair_index[27];
  int pair_size[27];
};

/**
 * @brief Compute the midpoint and surface area of the face with the given
 * vertices.
 *
 * @param ax, ay, bx, by Face vertices.
 * @param result Midpoint of the face.
 * @return Surface area of the face.
 */
static inline double voronoi_compute_midpoint_area_face(double ax, double ay,
                                                        double bx, double by,
                                                        double *result) {

  result[0] = 0.5 * (ax + bx);
  result[1] = 0.5 * (ay + by);

  double sx = bx - ax;
  double sy = by - ay;

  return sqrt(sx * sx + sy * sy);
}

/**
 * @brief Add a two particle pair to the grid.
 *
 * The grid connectivity is stored per cell sid: sid=0 corresponds to particle
 * pairs encountered during a self task (both particles are within the local
 * cell), while sid=1-26 correspond to particle interactions for which the right
 * neighbour is part of one of the 26 neighbouring cells.
 *
 * For each pair, we compute and store all the quantities required to compute
 * fluxes between the Voronoi cells: the surface area and midpoint of the
 * interface.
 *
 * @param v Voronoi grid.
 * @param sid Index of the cell list in which the pair is stored.
 * @param lid Index of the left particle within its cell (the cell linked to
 * this grid).
 * @param rid Index of the right particle within cell sid.
 * @param ax,ay,bx,by Vertices of the interface.
 */
static inline void voronoi_add_pair(struct voronoi *restrict v, int sid,
                                    int lid, int rid, double ax, double ay,
                                    double bx, double by) {

  if (v->pair_index[sid] == v->pair_size[sid]) {
    v->pair_size[sid] <<= 1;
    v->pairs[sid] = (struct voronoi_pair *)realloc(
        v->pairs[sid], v->pair_size[sid] * sizeof(struct voronoi_pair));
  }
  struct voronoi_pair *this_pair = &v->pairs[sid][v->pair_index[sid]];
  this_pair->left = lid;
  this_pair->right = rid;
  this_pair->surface_area =
      voronoi_compute_midpoint_area_face(ax, ay, bx, by, this_pair->midpoint);
#ifdef VORONOI_STORE_CONNECTIONS
  this_pair->a[0] = ax;
  this_pair->a[1] = ay;
  this_pair->b[0] = bx;
  this_pair->b[1] = by;
#endif
  ++v->pair_index[sid];
}

/**
 * @brief Compute the volume and centroid of the triangle through the given 3
 * points.
 *
 * @param ax, ay, bx, by, cx, cy Point coordinates.
 * @param result Centroid of the triangle.
 * @return Volume of the triangle.
 */
static inline double voronoi_compute_centroid_volume_triangle(
    double ax, double ay, double bx, double by, double cx, double cy,
    double *result) {

  result[0] = (ax + bx + cx) / 3.;
  result[1] = (ay + by + cy) / 3.;

  double s10x = bx - ax;
  double s10y = by - ay;

  double s20x = cx - ax;
  double s20y = cy - ay;

  return 0.5 * fabs(s10x * s20y - s20x * s10y);
}

/**
 * @brief Initialise the Voronoi grid based on the given Delaunay tessellation.
 *
 * This function allocates the memory for the Voronoi grid arrays and creates
 * the grid in linear time by
 *  1. Computing the grid vertices as the midpoints of the circumcircles of the
 *     Delaunay triangles.
 *  2. Looping over all vertices and for each vertex looping (in
 *     counterclockwise order) over all triangles that link to that vertex.
 *
 * During the second step, the geometrical properties (cell centroid, volume
 * and face midpoint, area) are computed as well.
 *
 * @param v Voronoi grid.
 * @param d Delaunay tessellation (read-only).
 */
static inline void voronoi_init(struct voronoi *restrict v,
                                const struct delaunay *restrict d,
                                const struct part *restrict parts) {

  delaunay_assert(d->vertex_end > 0);

  /* the number of cells equals the number of non-ghost and non-dummy vertices
     in the Delaunay tessellation */
  v->number_of_cells = d->vertex_end - d->vertex_start;
  /* allocate memory for the generators and the vertices */
  v->cells = (struct voronoi_cell_new *)malloc(v->number_of_cells *
                                               sizeof(struct voronoi_cell_new));

  /* loop over the triangles in the Delaunay tessellation and compute the
     midpoints of their circumcircles. These happen to be the vertices of the
     Voronoi grid (because they are the points of equal distance to 3
     generators, while the Voronoi edges are the lines of equal distance to 2
     generators) */
  /* FUTURE NOTE: we can add a check here to see if the triangle is linked to
     a non-ghost, non-dummy vertex. If it isn't, it is not a grid vertex and
     we can skip it. */
  double *vertices =
      (double *)malloc(2 * (d->triangle_index - 3) * sizeof(double));
  for (int i = 0; i < d->triangle_index - 3; ++i) {
    struct triangle *t = &d->triangles[i + 3];
    int v0 = t->vertices[0];
    int v1 = t->vertices[1];
    int v2 = t->vertices[2];

    /* skip triangles that are not connected to any local vertex */
    if (v0 >= v->number_of_cells && v1 >= v->number_of_cells &&
        v2 >= v->number_of_cells) {
      continue;
    }

    double v0x, v0y, v1x, v1y, v2x, v2y;
    if (v0 < d->ngb_offset) {
      v0x = parts[v0].x[0];
      v0y = parts[v0].x[1];
    } else {
      v0x = d->vertices[2 * v0];
      v0y = d->vertices[2 * v0 + 1];
    }
    if (v1 < d->ngb_offset) {
      v1x = parts[v1].x[0];
      v1y = parts[v1].x[1];
    } else {
      v1x = d->vertices[2 * v1];
      v1y = d->vertices[2 * v1 + 1];
    }
    if (v2 < d->ngb_offset) {
      v2x = parts[v2].x[0];
      v2y = parts[v2].x[1];
    } else {
      v2x = d->vertices[2 * v2];
      v2y = d->vertices[2 * v2 + 1];
    }

    double ax = v1x - v0x;
    double ay = v1y - v0y;
    double bx = v2x - v0x;
    double by = v2y - v0y;

    double D = 2. * (ax * by - ay * bx);
    double a2 = ax * ax + ay * ay;
    double b2 = bx * bx + by * by;
    double Rx = (by * a2 - ay * b2) / D;
    double Ry = (ax * b2 - bx * a2) / D;

    vertices[2 * i] = v0x + Rx;
    vertices[2 * i + 1] = v0y + Ry;
  }

  for (int i = 0; i < 27; ++i) {
    v->pairs[i] =
        (struct voronoi_pair *)malloc(10 * sizeof(struct voronoi_pair));
    v->pair_index[i] = 0;
    v->pair_size[i] = 10;
  }
  /* loop over all cell generators, and hence over all non-ghost, non-dummy
     Delaunay vertices */
  for (int i = 0; i < v->number_of_cells; ++i) {

    struct voronoi_cell_new *this_cell = &v->cells[i];
    double cell_volume = 0.;
    double cell_centroid[2] = {0., 0.};
    double centroid[2];
    int nface = 1;

    /* get the generator position, we use it during centroid/volume
       calculations */
    double ax, ay;
    if (i < d->ngb_offset) {
      ax = parts[i].x[0];
      ay = parts[i].x[1];
    } else {
      ax = d->vertices[2 * i];
      ay = d->vertices[2 * i + 1];
    }

#ifdef VORONOI_STORE_GENERATORS
    this_cell->generator[0] = ax;
    this_cell->generator[1] = ay;
#endif

    /* Get a triangle containing this generator and the index of the generator
       within that triangle */
    int dverti = i + d->vertex_start;
    int t0 = d->vertex_triangles[dverti];
    int vi0 = d->vertex_triangle_index[dverti];
    /* Add the first vertex for this cell: the circumcircle midpoint of this
       triangle */
    int vertex_index = t0 - 3;
    int first_vertex_index = vertex_index;

    /* store the current vertex position for geometry calculations */
    double cx = vertices[2 * vertex_index];
    double cy = vertices[2 * vertex_index + 1];

    /* now use knowledge of the triangle orientation convention to obtain the
       next neighbouring triangle that has this generator as vertex, in the
       counterclockwise direction */
    int vi0p1 = (vi0 + 1) % 3;

    int first_vertex = d->triangles[t0].vertices[vi0p1];

    int t1 = d->triangles[t0].neighbours[vi0p1];
    int vi1 = d->triangles[t0].index_in_neighbour[vi0p1];
    /* loop around until we arrive back at the original triangle */
    while (t1 != t0) {
      ++nface;
      vertex_index = t1 - 3;

      /* get the current vertex position for geometry calculations.
         Each calculation involves the current and the previous vertex.
         The face geometry is completely determined by these (the face is in
         this case simply the line segment between (bx,by) and (cx,cy).
         The cell geometry is calculated by accumulating the centroid and
         "volume" for the triangle (ax, ay) - (bx, by) - (cx, cy). */
      double bx = cx;
      double by = cy;
      cx = vertices[2 * vertex_index];
      cy = vertices[2 * vertex_index + 1];

      double V = voronoi_compute_centroid_volume_triangle(ax, ay, bx, by, cx,
                                                          cy, centroid);
      cell_volume += V;
      cell_centroid[0] += V * centroid[0];
      cell_centroid[1] += V * centroid[1];

      int vi1p2 = (vi1 + 2) % 3;

      /* the neighbour corresponding to the face is the same vertex that
         determines the next triangle */
      int other_vertex = d->triangles[t1].vertices[vi1p2];
      if (other_vertex < d->ngb_offset) {
        if (other_vertex > dverti) {
          /* only store pairs once */
          voronoi_add_pair(v, 0, dverti, other_vertex, bx, by, cx, cy);
        }
      } else {
        /* no check on other_vertex > i required, since this is always true */
        int sid = d->ngb_cells[other_vertex - d->ngb_offset];
        int pid = d->ngb_indices[other_vertex - d->ngb_offset];
        voronoi_add_pair(v, sid, dverti, pid, bx, by, cx, cy);
      }

      vi1 = d->triangles[t1].index_in_neighbour[vi1p2];
      t1 = d->triangles[t1].neighbours[vi1p2];
    }

    /* don't forget the last edge for the geometry! */
    double bx = cx;
    double by = cy;
    cx = vertices[2 * first_vertex_index];
    cy = vertices[2 * first_vertex_index + 1];

    double V = voronoi_compute_centroid_volume_triangle(ax, ay, bx, by, cx, cy,
                                                        centroid);
    cell_volume += V;
    cell_centroid[0] += V * centroid[0];
    cell_centroid[1] += V * centroid[1];

    if (first_vertex < d->ngb_offset) {
      if (first_vertex > dverti) {
        /* only store pairs once */
        voronoi_add_pair(v, 0, dverti, first_vertex, bx, by, cx, cy);
      }
    } else {
      /* no check on other_vertex > i required, since this is always true */
      int sid = d->ngb_cells[first_vertex - d->ngb_offset];
      int pid = d->ngb_indices[first_vertex - d->ngb_offset];
      voronoi_add_pair(v, sid, i, pid, bx, by, cx, cy);
    }

    /* now compute the actual centroid by dividing the volume-weighted
       accumulators by the cell volume */
    cell_centroid[0] /= cell_volume;
    cell_centroid[1] /= cell_volume;
    this_cell->volume = cell_volume;
    this_cell->centroid[0] = cell_centroid[0];
    this_cell->centroid[1] = cell_centroid[1];
#ifdef VORONOI_STORE_CELL_STATS
    this_cell->nface = nface;
#endif
  }

  free(vertices);
}

/**
 * @brief Free up all memory used by the Voronoi grid.
 *
 * @param v Voronoi grid.
 */
static inline void voronoi_destroy(struct voronoi *restrict v) {
  free(v->cells);
  for (int i = 0; i < 27; ++i) {
    free(v->pairs[i]);
  }
}

/**
 * @brief Sanity checks on the grid.
 *
 * Right now, this only checks the total volume of the cells.
 */
static inline void voronoi_check_grid(const struct voronoi *restrict v) {
  double V = 0.;
  for (int i = 0; i < v->number_of_cells; ++i) {
    V += v->cells[i].volume;
  }

  printf("Total volume: %g\n", V);
}

static inline void voronoi_write_grid(const struct voronoi *restrict v,
                                      FILE *file) {

#ifdef VORONOI_STORE_GENERATORS
  for (int i = 0; i < v->number_of_cells; ++i) {
    struct voronoi_cell_new *this_cell = &v->cells[i];
    fprintf(file, "G\t%g\t%g\n", this_cell->generator[0],
            this_cell->generator[1]);
  }
#endif
  for (int ngb = 0; ngb < 27; ++ngb) {
    for (int i = 0; i < v->pair_index[ngb]; ++i) {
      struct voronoi_pair *pair = &v->pairs[ngb][i];
#ifdef VORONOI_STORE_CONNECTIONS
      fprintf(file, "F\t%g\t%g\t%g\t%g\t%i\t%i\t%i\n", pair->a[0], pair->a[1],
              pair->b[0], pair->b[1], pair->left, ngb, pair->right);
#else
      fprintf(file, "F\t%i\t%i\t%i\n", pair->left, ngb, pair->right);
#endif
    }
  }
}

/**
 * @brief Print the Voronoi grid to a file with the given name.
 *
 * The grid is output as follows:
 *  1. First, each generator is output, together with all its connections.
 *     The generator is output as "G\tx\ty\n", where x and y are the coordinates
 *     of the generator. The centroid of the corresponding cell is output as
 *     "M\tx\ty\n".
 *     The connections are output as "C\tindex\tindex\n", where the two indices
 *     are the indices of two vertices of the grid, in the order output by 2.
 *     The midpoint of each edge is output as "F\tx\ty\n".
 *  2. Next, all vertices of the grid are output, in the format "V\tx\ty\n".
 *
 * @param v Voronoi grid (read-only).
 * @param file_name Name of the output file.
 */
static inline void voronoi_print_grid(const struct voronoi *restrict v,
                                      const char *file_name) {

  FILE *file = fopen(file_name, "w");

  voronoi_write_grid(v, file);

  fclose(file);
}

#endif /* SWIFT_VORONOI_H */
