# Define the system of units to use internally.
InternalUnitSystem:
  UnitMass_in_cgs:     1.988e+33 # Solar mass
  UnitLength_in_cgs:   3.086e+21 # kpc
  UnitVelocity_in_cgs: 1e5       # km / s
  UnitCurrent_in_cgs:  1         # Amperes
  UnitTemp_in_cgs:     1         # Kelvin
  
# Parameters for the self-gravity scheme
Gravity:
  eta:          0.025                # Constant dimensionless multiplier for time integration.
  MAC:          geometric
  theta_cr:     0.7                  # Opening angle (Multipole acceptance criterion).
  max_physical_DM_softening: 0.7     # Physical softening length (in internal units).


# Parameters governing the time integration (Set dt_min and dt_max to the same value for a fixed time-step run.)
TimeIntegration:
  time_begin:        0.    # The starting time of the simulation (in internal units).
  time_end:          0.1    # The end time of the simulation (in internal units).
  dt_min:            1e-6  # The minimal time-step size of the simulation (in internal units).
  dt_max:            1e-2  # The maximal time-step size of the simulation (in internal units).

# Parameters governing the snapshots
Snapshots:
  basename:   output      # Common part of the name of output files
  delta_time: 0.01         # Time difference between consecutive outputs (in internal units)

# Parameters governing the conserved quantities statistics
Statistics:
  delta_time:           1e-1     # Time between statistics output

# Parameters related to the initial conditions
InitialConditions:
  file_name:          sidm_ics.hdf5 # The file to read
  periodic:           0
