#!/usr/bin/env python3
################################################################################
# This file is part of SWIFT.
# Copyright (c) 2026 Darwin Roduit (darwin.roduit@epfl.ch)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
"""Generate initial conditions for a turbulent, collapsing molecular cloud.

A uniform-density sphere of gas is seeded with a turbulent velocity field
built from a power-law power spectrum P(k) = k^exponent, sampled on a
periodic FFT mesh and interpolated onto the particles. --solenoidal_fraction
sets the exact fraction of the turbulent kinetic energy that is solenoidal
(divergence-free) vs. compressive (curl-free), continuously between 0
(purely compressive) and 1 (purely solenoidal); 2/3 reproduces the natural,
unprojected isotropic mixture of the two.

Note on provenance: this replaces a pNbody-based generator
(pNbody.power_spectra.PerturbationPowerSpectrum) that used to live outside
this repository. That class implemented a Zel'dovich-type displacement field
(Psi(k) proportional to k/k^2), which is a purely compressive construction by
design -- appropriate for cosmological ICs, but not a generator that can
produce a genuinely divergence-free "solenoidal" velocity field. Measuring
the longitudinal/transverse power ratio of the three archived cloud ICs this
repository used to ship (labelled solenoidal/compressive/mixed) confirms this:
all three have essentially the isotropic ~1/3 longitudinal fraction, i.e. none
of them were actually Helmholtz-projected. The turbulence generator below
draws an independent random vector field per Fourier mode, splits it exactly
into its Helmholtz components, and recombines them with weights set by
--solenoidal_fraction, so this parameter now does what its name says.
"""

import argparse

import h5py
import numpy as np
from astropy import constants as cte
from astropy import units as u

################################################################################
# Sphere model
################################################################################


class HomogeneousSphere:
    """Sphere of constant density."""

    def __init__(self, R_s, M_tot=None, rho_0=None, G=1.0):
        if M_tot is not None:
            self.M_tot = M_tot
            self.rho_0 = M_tot / (4.0 / 3.0 * np.pi * R_s**3)
        elif rho_0 is not None:
            self.rho_0 = rho_0
            self.M_tot = 4.0 / 3.0 * np.pi * R_s**3 * rho_0
        else:
            raise ValueError("Provide either M_tot or rho_0.")
        self.G = G
        self.R_s = R_s

    def free_fall_time(self):
        return np.sqrt(3 * np.pi / (32 * self.G * self.rho_0))

    def potential_energy(self):
        """Analytic gravitational self-energy of a uniform-density sphere."""
        return -3.0 / 5.0 * self.G * self.M_tot**2 / self.R_s

    def generate_particles(self, n, seed):
        rng = np.random.default_rng(seed=seed)

        random1 = rng.random(n)
        random2 = rng.random(n)
        random3 = rng.random(n)

        r = self.R_s * random1 ** (1.0 / 3.0)
        phi = random2 * 2.0 * np.pi
        costh = 1.0 - 2.0 * random3
        sinth = np.sqrt(1.0 - costh**2)

        x = r * sinth * np.cos(phi)
        y = r * sinth * np.sin(phi)
        z = r * costh

        pos = np.transpose(np.array([x, y, z]))
        vel = np.zeros([n, 3])
        mass = np.ones(n) * self.M_tot / n

        return pos, vel, mass


################################################################################
# Turbulent velocity field
################################################################################


class TurbulentVelocityField:
    """Build a periodic, isotropic turbulent velocity field on an FFT mesh from
    a power-law power spectrum, and interpolate it onto arbitrary positions.

    The field is generated by drawing real Gaussian white noise for each of
    the three velocity components directly on the mesh and Fourier
    transforming it: a real input field always has a Hermitian-symmetric
    transform, so this sidesteps having to symmetrize the Fourier coefficients
    by hand. Multiplying by sqrt(P(k)) then imposes the desired power
    spectrum while preserving that symmetry (P(k) is real and depends only on
    |k|).

    The field is then split exactly into its Helmholtz components -- transverse
    (solenoidal, divergence-free) and longitudinal (compressive, curl-free) --
    each renormalised to carry all of the field's power on its own, and
    recombined with weights set by solenoidal_fraction (zeta): the transverse
    part gets weight sqrt(zeta), the longitudinal part sqrt(1-zeta). Because
    the two parts are exactly orthogonal mode-by-mode (Parseval), this makes
    the *realised* solenoidal energy fraction of the output exactly zeta, not
    just its expectation value: zeta=1 is purely solenoidal, zeta=0 purely
    compressive, and zeta=2/3 reproduces the natural, unprojected isotropic
    mixture of the two (a raw random 3-vector field has 2 of its 3 degrees of
    freedom transverse and 1 longitudinal).
    """

    def __init__(self, boxsize, N_mesh, exponent, seed):
        self.boxsize = boxsize
        self.N_mesh = N_mesh
        self.exponent = exponent
        self.seed = seed

    def _k_grid(self):
        kfreq = 2 * np.pi * np.fft.fftfreq(self.N_mesh, d=self.boxsize / self.N_mesh)
        KX, KY, KZ = np.meshgrid(kfreq, kfreq, kfreq, indexing="ij")
        k = np.stack([KX, KY, KZ])
        k_norm = np.linalg.norm(k, axis=0)
        return k, k_norm

    def generate(self, solenoidal_fraction):
        if not 0.0 <= solenoidal_fraction <= 1.0:
            raise ValueError("solenoidal_fraction must be in [0, 1].")

        rng = np.random.default_rng(seed=self.seed)
        white = rng.normal(size=(3, self.N_mesh, self.N_mesh, self.N_mesh))
        white_hat = np.fft.fftn(white, axes=(1, 2, 3))

        k, k_norm = self._k_grid()
        k_nyquist = np.pi * self.N_mesh / self.boxsize

        with np.errstate(divide="ignore", invalid="ignore"):
            power = k_norm**self.exponent
        power[k_norm == 0] = 0.0  # No net bulk motion from the k=0 mode.
        power[k_norm > k_nyquist] = 0.0

        field_hat = white_hat * np.sqrt(power)

        k_hat = np.divide(k, k_norm, out=np.zeros_like(k), where=k_norm > 0)
        longitudinal = np.sum(field_hat * k_hat, axis=0) * k_hat
        transverse = field_hat - longitudinal

        transverse /= np.sqrt(np.sum(np.abs(transverse) ** 2))
        longitudinal /= np.sqrt(np.sum(np.abs(longitudinal) ** 2))

        field_hat = (
            np.sqrt(solenoidal_fraction) * transverse
            + np.sqrt(1.0 - solenoidal_fraction) * longitudinal
        )

        return np.fft.ifftn(field_hat, axes=(1, 2, 3)).real

    def interpolate(self, field, positions):
        """Trilinear interpolation of a (3, N_mesh, N_mesh, N_mesh) mesh field
        onto the given (N, 3) positions, assuming a periodic box of side
        self.boxsize starting at the origin."""
        grid_pos = (positions % self.boxsize) / self.boxsize * self.N_mesh
        i = np.floor(grid_pos).astype(np.int64) % self.N_mesh
        frac = grid_pos - np.floor(grid_pos)
        ii = (i + 1) % self.N_mesh

        f000 = field[:, i[:, 0], i[:, 1], i[:, 2]]
        f001 = field[:, i[:, 0], i[:, 1], ii[:, 2]]
        f010 = field[:, i[:, 0], ii[:, 1], i[:, 2]]
        f011 = field[:, i[:, 0], ii[:, 1], ii[:, 2]]
        f100 = field[:, ii[:, 0], i[:, 1], i[:, 2]]
        f101 = field[:, ii[:, 0], i[:, 1], ii[:, 2]]
        f110 = field[:, ii[:, 0], ii[:, 1], i[:, 2]]
        f111 = field[:, ii[:, 0], ii[:, 1], ii[:, 2]]

        fx, fy, fz = frac[:, 0], frac[:, 1], frac[:, 2]
        result = (
            f000 * (1 - fx) * (1 - fy) * (1 - fz)
            + f001 * (1 - fx) * (1 - fy) * fz
            + f010 * (1 - fx) * fy * (1 - fz)
            + f011 * (1 - fx) * fy * fz
            + f100 * fx * (1 - fy) * (1 - fz)
            + f101 * fx * (1 - fy) * fz
            + f110 * fx * fy * (1 - fz)
            + f111 * fx * fy * fz
        )
        return result.transpose()


################################################################################
# CLI
################################################################################


def parse_options():
    description = """Generate a turbulent, collapsing molecular cloud: a
homogeneous sphere seeded with a power-law turbulent velocity field."""
    epilog = """
Examples
--------
python3 makeIC.py -o cloud.hdf5
python3 makeIC.py -o cloud.hdf5 -N 500000 --solenoidal_fraction 0.0    # purely compressive
python3 makeIC.py -o cloud.hdf5 -N 500000 --solenoidal_fraction 0.667  # natural mixture
python3 makeIC.py -o cloud.hdf5 -N 4000000 --solenoidal_fraction 1.0  # purely solenoidal
"""
    parser = argparse.ArgumentParser(
        description=description,
        epilog=epilog,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "-o",
        dest="outputfilename",
        default="collapsing_cloud.hdf5",
        help="Name of the output file.",
    )
    parser.add_argument(
        "-N",
        dest="N",
        type=int,
        default=100000,
        help="Number of gas particles. The original test that motivated this "
        "example used 4e6 particles; that is a multi-hour IC generation and "
        "a much longer run, so raise this for production/paper-quality runs.",
    )
    parser.add_argument(
        "--R_s",
        type=float,
        default=20054.0,
        help="Radius of the cloud, in AU.",
    )
    parser.add_argument(
        "--M_tot",
        type=float,
        default=100.0,
        help="Total gas mass, in solar masses.",
    )
    parser.add_argument(
        "--T",
        dest="T",
        type=float,
        default=10.0,
        help="Isothermal gas temperature, in Kelvin. Sets the (fixed) thermal "
        "energy per unit mass; unlike Boss & Bodenheimer, this cloud's support "
        "against collapse is meant to come from turbulence (--E_kin_over_E_pot), "
        "not from thermal pressure, so this is set from a physical temperature "
        "rather than from a target thermal/gravitational energy ratio.",
    )
    parser.add_argument(
        "--mu",
        type=float,
        default=2.3,
        help="Mean molecular weight of the gas.",
    )
    parser.add_argument(
        "--E_kin_over_E_pot",
        type=float,
        default=1.0,
        help="Ratio of turbulent kinetic energy to |E_pot|, used to normalise "
        "the turbulent velocity field.",
    )
    parser.add_argument(
        "--solenoidal_fraction",
        type=float,
        default=1.0,
        help="Fraction of the turbulent kinetic energy that is solenoidal "
        "(divergence-free) rather than compressive (curl-free), in [0, 1]. "
        "1.0 is purely solenoidal, 0.0 purely compressive, and 2/3 reproduces "
        "the natural, unprojected isotropic mixture of the two.",
    )
    parser.add_argument(
        "--exponent",
        type=float,
        default=-4.0,
        help="Power-law exponent of the velocity power spectrum P(k) ~ k^exponent.",
    )
    parser.add_argument(
        "--N_mesh",
        type=int,
        default=128,
        help="Size of the FFT mesh used to generate the turbulent field. "
        "Should be at least the number of particles per dimension, N^(1/3).",
    )
    parser.add_argument(
        "--v_max_cut",
        type=float,
        default=1e3,
        help="Clip turbulent velocities above this value, in km/s.",
    )
    parser.add_argument(
        "--boxsize",
        type=float,
        default=None,
        help="Side length of the (cubic) box, in AU. Defaults to 2.5 times the "
        "maximal particle distance from the centre.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=1,
        help="Random seed.",
    )

    return parser.parse_args()


################################################################################
# Main
################################################################################

if __name__ == "__main__":
    opt = parse_options()

    # Units: AU / solar mass / km/s (matching the InternalUnitSystem in params.yml)
    u_Length = 1 * u.AU
    u_Mass = 1 * u.M_sun
    u_Velocity = 1 * u.km / u.s
    u_Time = u_Length.to(u.km) / u_Velocity

    UnitLength_in_cgs = u_Length.to(u.cm).value
    UnitMass_in_cgs = u_Mass.to(u.g).value
    UnitVelocity_in_cgs = u_Velocity.to(u.cm / u.s).value
    UnitTime_in_cgs = u_Time.to(u.s).value

    G = cte.G.to(u_Length**3 / (u_Mass * u_Time**2)).value

    R_s = opt.R_s
    M_tot = (opt.M_tot * u.M_sun).to(u_Mass).value
    N = opt.N

    sphere = HomogeneousSphere(R_s=R_s, M_tot=M_tot, G=G)
    t_ff = sphere.free_fall_time()
    E_pot = sphere.potential_energy()

    print("Collapsing turbulent cloud")
    print("--------------------------")
    print(f"  N            = {N}")
    print(f"  R_s          = {R_s:.3e} AU")
    print(f"  M_tot        = {M_tot:.3e} M_sun")
    print(f"  rho_0        = {sphere.rho_0:.3e} (code units)")
    print(f"  t_ff         = {t_ff:.3e} (code units)")
    print(f"  E_pot        = {E_pot:.3e} (code units, analytic uniform-sphere value)")

    pos, vel, mass = sphere.generate_particles(N, seed=opt.seed)
    rho = np.full(N, sphere.rho_0)

    # Isothermal internal energy per unit mass: u = k_B*T / ((gamma-1)*mu*m_p)
    gamma = 5.0 / 3.0
    u_iso = (
        (cte.k_B * opt.T * u.K / ((gamma - 1) * opt.mu * cte.m_p))
        .to(u_Velocity**2)
        .value
    )
    U_int_per_part = np.full(N, u_iso)
    U_int_total = u_iso * M_tot
    alpha = U_int_total / abs(E_pot)
    print(f"  T            = {opt.T:.3e} K")
    print(
        f"  alpha        = U_therm/|E_pot| = {alpha:.3e} (derived from T, not an input)"
    )
    print(
        f"  This run uses the isothermal EoS: set params.yml's "
        f"EoS:isothermal_internal_energy to {U_int_per_part[0]:.6e} to match."
    )

    # Boxsize and smoothing length
    r_max = np.max(np.linalg.norm(pos, axis=1))
    L = opt.boxsize if opt.boxsize is not None else 2.5 * r_max
    h = np.full(N, R_s / N ** (1.0 / 3.0))

    N_sample = int(np.ceil(np.cbrt(N)))
    if opt.N_mesh < N_sample:
        print(
            f"\nWarning: N_mesh ({opt.N_mesh}) < N^(1/3) ({N_sample}); the "
            "turbulent field will be under-resolved relative to the particle "
            "sampling."
        )

    print(
        f"\nGenerating turbulent velocity field (solenoidal_fraction="
        f"{opt.solenoidal_fraction:.3f})..."
    )
    turbulence = TurbulentVelocityField(
        boxsize=L, N_mesh=opt.N_mesh, exponent=opt.exponent, seed=opt.seed
    )
    field = turbulence.generate(opt.solenoidal_fraction)
    # Sample on a periodic grid centred on the sphere; positions are shifted so
    # the sphere's centre (0,0,0) sits at the middle of the periodic box.
    turb_vel = turbulence.interpolate(field, pos + L / 2.0)

    # Rescale to the desired ratio of turbulent kinetic energy to |E_pot|
    E_kin_turb = 0.5 * np.sum(mass * np.sum(turb_vel**2, axis=1))
    turb_vel *= np.sqrt(opt.E_kin_over_E_pot * abs(E_pot) / E_kin_turb)

    v_norm = np.linalg.norm(turb_vel, axis=1)
    turb_vel[v_norm > opt.v_max_cut] = 0.0

    vel = vel + turb_vel
    vel -= np.average(vel, axis=0, weights=mass)  # Remove net momentum.

    E_kin = 0.5 * np.sum(mass * np.sum(vel**2, axis=1))
    print(f"  E_kin        = {E_kin:.3e} (code units)")
    print(f"  E_kin/|E_pot| = {E_kin / abs(E_pot):.3e}")

    print(f"  boxsize      = {L:.3e} AU")
    print(f"  shift        = {L / 2:.3e} AU (set this in params.yml)")

    ids = np.arange(N, dtype=np.uint64)

    with h5py.File(opt.outputfilename, "w") as f:
        grp = f.create_group("/Header")
        grp.attrs["BoxSize"] = [L, L, L]
        grp.attrs["NumPart_Total"] = [N, 0, 0, 0, 0, 0]
        grp.attrs["NumPart_Total_HighWord"] = [0, 0, 0, 0, 0, 0]
        grp.attrs["NumPart_ThisFile"] = [N, 0, 0, 0, 0, 0]
        grp.attrs["Time"] = 0.0
        grp.attrs["NumFileOutputsPerSnapshot"] = 1
        grp.attrs["MassTable"] = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        grp.attrs["Flag_Entropy_ICs"] = 0
        grp.attrs["Dimension"] = 3

        grp = f.create_group("/Units")
        grp.attrs["Unit length in cgs (U_L)"] = UnitLength_in_cgs
        grp.attrs["Unit mass in cgs (U_M)"] = UnitMass_in_cgs
        grp.attrs["Unit time in cgs (U_t)"] = UnitTime_in_cgs
        grp.attrs["Unit current in cgs (U_I)"] = 1.0
        grp.attrs["Unit temperature in cgs (U_T)"] = 1.0

        grp = f.create_group("/PartType0")
        grp.create_dataset("Coordinates", data=pos, dtype="d")
        grp.create_dataset("Velocities", data=vel, dtype="f")
        grp.create_dataset("Masses", data=mass, dtype="f")
        grp.create_dataset("SmoothingLength", data=h, dtype="f")
        grp.create_dataset("InternalEnergy", data=U_int_per_part, dtype="f")
        grp.create_dataset("ParticleIDs", data=ids, dtype="L")
        grp.create_dataset("Densities", data=rho, dtype="f")

    print(f"\n{opt.outputfilename} saved.")
