"""Plot the cell geometry given a set of diagnostic files.

This script generates a 2D grid diagram of cells with a nested region
based on diagnostic files generated by running SWIFT with --zoom-geometry.

Example:
    python plot_zoom_geometry.py --metadata zoom_metadata.yml --cells zoom_cell_data.dat
"""

import argparse
import yaml
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.lines import Line2D


def load_data(meta_file, data_file):
    """Load metadata and cell data."""
    with open(meta_file, "r") as f:
        metadata = yaml.safe_load(f)

    # Load cell data: CellID Type Subtype Rank LocX LocY LocZ WidthX WidthY WidthZ MaxDepth Gas DM DM_Bkg Sink Stars BH Neutrino
    data = np.loadtxt(data_file)

    return metadata, data


def draw_grid(metadata, data, show=False):
    """Draw the grid diagram of the cells."""
    # Setup the figure
    fig, ax = plt.subplots(figsize=(6, 6))
    ax.set_aspect("equal")
    box_size = metadata["BoxSize"][0]
    ax.set_xlim(0, box_size)
    ax.set_ylim(0, box_size)

    # Draw each cell
    for row in data:
        # cell_id = int(row[0])
        ctype = int(row[1])  # 0=regular, 1=zoom, 2=bkg
        loc = row[4:7]
        width = row[7:10]

        # Define color based on cell type
        if ctype == 2:  # background
            color = "#bbe6e4"
            order = 0
        elif ctype == 1:  # zoom
            color = "#084b83"
            order = 2
        else:
            continue  # regular cells don't need drawing in zoom context

        ax.add_patch(
            Rectangle(
                (loc[0], loc[1]),
                width[0],
                width[1],
                fill=True,
                facecolor=color,
                edgecolor="black",
                zorder=order,
                alpha=0.9,
            )
        )

    # Define handles for the legend
    handles = [
        Line2D(
            [0],
            [0],
            marker="s",
            color="w",
            markerfacecolor="#bbe6e4",
            markeredgecolor="black",
            markersize=15,
            label="Background",
            alpha=0.9,
        ),
        Line2D(
            [0],
            [0],
            marker="s",
            color="w",
            markerfacecolor="#084b83",
            markeredgecolor="black",
            markersize=15,
            label="Zoom",
            alpha=0.9,
        ),
    ]

    # Place a legend below the x axis with the cell types
    ax.legend(
        handles=handles,
        loc="upper center",
        bbox_to_anchor=(0.5, -0.05),
        ncol=len(handles),
        frameon=False,
    )

    # Save the figure
    fig.savefig("zoom_geometry.png", dpi=300)
    print("Saved zoom_geometry.png")
    if show:
        plt.show()
    plt.close(fig)


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Draw 2D grid from diagnostic files.")
    parser.add_argument(
        "--metadata", default="zoom_metadata.yml", help="Metadata YAML file"
    )
    parser.add_argument(
        "--cells", default="zoom_cell_data.dat", help="Cell data table file"
    )
    parser.add_argument(
        "--show", action="store_true", help="Show the plot interactively"
    )
    args = parser.parse_args()

    metadata, data = load_data(args.metadata, args.cells)
    draw_grid(metadata, data, show=args.show)


if __name__ == "__main__":
    main()
