
labels = [
    ["engine_split_gas_particles:", 1],
    ["Gpart assignment", 4],
    ["Mesh communication", 4],
    ["Forward Fourier transform", 4],
    ["Green function", 4],
    ["Backwards Fourier transform", 4],
    ["Gpart mesh forces", 4],
    ["engine_recompute_displacement_constraint:", 1],
    ["engine_exchange_top_multipoles:", 1],
    ["updating particle counts", 1],
    ["engine_estimate_nr_tasks:", 1],
    ["Making gravity tasks", 1],
    ["Making hydro tasks", 1],
    ["Splitting tasks", 1],
    ["Counting and linking tasks", 1],
    ["Setting super-pointers", 1],
    ["Making extra hydroloop tasks", 1],
    ["Linking gravity tasks", 1],
    ["Creating send tasks", 1],
    ["Exchanging cell tags", 1],
    ["Creating recv tasks", 1],
    ["Counting number of foreign particles", 1],
    ["Recursively linking foreign arrays", 1],
    ["Setting unlocks", 1],
    ["Ranking the tasks", 1],
    ["scheduler_reweight:", 1],
    ["space_list_useful_top_level_cells:", 1],
    ["space_rebuild:", 1],
    ["scheduler_report_task_times:", 1],
    ["engine_drift_all:", 0],
    ["engine_unskip:", 0],
    ["engine_unskip_timestep_communications:", 0],
    ["engine_collect_end_of_step:", 0],
    ["engine_launch: \(tasks\)", 0],
    ["engine_launch: \(timesteps\)", 0],
    ["writing particle properties", 0],
    ["engine_repartition:", 0],
    ["engine_exchange_cells:", 1],
    ["Dumping restart files", 0],
    ["engine_print_stats:", 0],
    ["engine_marktasks:", 1],
    ["Reading initial conditions", 0],
    ["engine_print_task_counts:", 0],
    ["engine_drift_top_multipoles:", 0],
    ["Communicating rebuild flag", 0],
    ["Writing step info to files", 0],
    ["Updating general quantities", 0],
    ["task_dump_all:", 0],
    ["task_dump_stats:", 0],
    ["task_dump_active:", 0],
    ["restart_read:", 0],
    ["engine_split:", 0],
    ["space_init", 0],
    ["engine_init", 0],
    ["engine_repartition_trigger:", 0],
    ["VR Collecting top-level cell info", 3],
    ["VR Collecting particle info", 3],
    ["VR Invocation of velociraptor", 3],
    ["VR Copying group information back", 3],
    ["fof_allocate:", 2],
    ["engine_make_fof_tasks:", 2],
    ["engine_activate_fof_tasks:", 2],
    ["fof_search_tree:", 2],
    ["engine_launch: \(fof\)", 2],
    ["engine_launch: \(fof comms\)", 2],
    ["do_line_of_sight:", 0],
    ["csds_log_all_particles:", 0],
    ["csds_ensure_size:", 0],
    ["csds_init:", 0],
]
