# Define the system of units to use internally.
InternalUnitSystem:
  UnitMass_in_cgs:     1.988409870698051e+43   # 10^10 solar masses
  UnitLength_in_cgs:   3.0856775814913673e+21  # 1 kpc
  UnitVelocity_in_cgs: 1e5 # km/s
  UnitCurrent_in_cgs:  1   # Amperes
  UnitTemp_in_cgs:     1   # Kelvin

# Parameters governing the time integration (Set dt_min and dt_max to the same value for a fixed time-step run.)
TimeIntegration:
  time_begin:        0.    # The starting time of the simulation (in internal units).
  time_end:          0.05  # The end time of the simulation (in internal units).
  dt_min:            1e-10 # The minimal time-step size of the simulation (in internal units).
  dt_max:            1e-2  # The maximal time-step size of the simulation (in internal units).

# Parameters governing the snapshots
Snapshots:
  subdir:     snap          # Directory to write the snapshots in 
  basename:   snapshot      # Common part of the name of output files
  time_first: 0.            # (Optional) Time of the first output if non-cosmological time-integration (in internal units)
  delta_time: 1e-3          # Time difference between consecutive outputs (in internal units)

Scheduler:
  cell_extra_gparts: 0      # (Optional) Number of spare sparts per top-level allocated at rebuild time for on-the-fly creation.
  cell_extra_sinks:  0      # (Optional) Number of spare sparts per top-level allocated at rebuild time for on-the-fly creation.
  cell_extra_sparts: 0      # (Optional) Number of spare sparts per top-level allocated at rebuild time for on-the-fly creation.
  max_top_level_cells: 3

# Parameters governing the conserved quantities statistics
Statistics:
  delta_time:           1e-1     # Time between statistics output
  time_first:             0.     # (Optional) Time of the first stats output if non-cosmological time-integration (in internal units)

# Parameters related to the initial conditions
InitialConditions:
  file_name:          ICs_homogeneous_box.hdf5
  periodic:               0       # Are we running with periodic ICs?
  shift:              [0.0,0.0,0.0]

# Parameters for the hydrodynamics scheme
SPH:
  resolution_eta:        1.2348   # Target smoothing length in units of the mean inter-particle separation (1.2348 == 57Ngbs with the Wendland C2 kernel).
  CFL_condition:         0.1      # Courant-Friedrich-Levy condition for time integration.
  minimal_temperature:   1

GEARChemistry:
  initial_metallicity: -1
  diffusion_coefficient : 2.516849e-1    # (Optional, GEAR (MF) diffusion only) Coefficient for the diffusion (see Shen et al. 2010; differs by gamma^2 due to h^2). Default: 1
  diffusion_mode:  Isotropic_constant    # Diffusion mode. Isotropic_constant = constant isotropic ; Smagorinsky = Smagorinsky (isotropic) ; Gradient = Gradient model (anisotropic). The diffusion_coefficient sets the normalisation of the diffusion.
  C_CFL_chemistry: 0.9                   # Courant-Friedrich-Levy condition for time integration of the diffusion equation.
  hll_riemann_solver_epsilon: 0.0        # (Optional) Tolerance parameter for the Hopkins 2017 HLL, eq (14). It must respect 0 <= epsilon <= 1. Default: 0.5
  hll_riemann_solver_psi:  0.1           # (Optional) Tolerance parameter (> 0) for artificial diffusion, eq (7) in Hi2017. (Default: 0.1)
  relaxation_time_mode:  Constant        # (Hyperbolic diffusion only) Relaxation time mode. Constant = constant relaxation time ; Turbulent = relaxation time based on gas shear tensor norm.
  tau: 1e-1                              # (Hyperbolic diffusion only) Relaxation time (physical and internal units) for the Constant relaxation time mode. In the Turbulent mode, this sets the normalisation of the final tau: pj.tau = tau/||Shear tensor||.

GEARFeedback:
  supernovae_energy_erg: 0.              # supernovae energy, used only for SNIa
  supernovae_efficiency: 0.              # supernovae energy efficiency, used for both SNIa and SNII
  yields_table: POPIIsw.h5
  yields_table_first_stars: POPIIsw.h5
  discrete_yields: 1
  imf_transition_metallicity: -5         # Maximal metallicity ([Fe/H]) for a first star (0 to deactivate).
  elements: [Fe, Mg, O, C, Al, Ca, Ba, Zn, Eu]              # Elements to read in the yields table. The number of element should be one less than the number of elements (N) requested during the configuration (--with-chemistry=GEAR_N).
